---
- name: Set retry variables
  set_fact:
    trex_app_cr_name: trex-app

- name: Deploy trex app (with retries)
  block:
    - name: include trex tasks to create app
      include_tasks: trex/app.yaml

    - name: Fail when run did not pass
      fail:
        msg: "TRex App run has failed"
      when: not trex_app_run_passed | default(false) | bool

  rescue:
    - name: delete trexconfig cr
      k8s:
        namespace: "{{ cnf_namespace }}"
        kind: TRexConfig
        name: "{{ trex_cr_name }}"
        state: absent

    - name: delete trexapp cr
      k8s:
        namespace: "{{ cnf_namespace }}"
        kind: TRexApp
        name: "{{ trex_app_cr_name }}"
        state: absent

    - name: check trex server pod to be deleted
      k8s_info:
        namespace: "{{ cnf_namespace }}"
        kind: Pod
        label_selectors:
          - example-cnf-type=pkt-gen
      register: trex_result
      retries: 30
      delay: 5
      until: "trex_result.resources|length == 0"

  always:
    - name: Retrieve TRex app logs
      community.kubernetes.k8s_log:
        namespace: "{{ cnf_namespace }}"
        label_selectors:
          - example-cnf-type=pkt-gen-app
          - job-name=job-{{ trex_app_cr_name }}
      register: trex_app_logs
      ignore_errors: true

    - name: Store logs when jobs_logs is defined
      copy:
        content: "{{ trex_app_logs.log }}"
        dest: "{{ job_logs.path }}/{{ trex_app_cr_name }}.log"
      when:
        - job_logs is defined
        - job_logs.path is defined
        - not trex_app_logs.failed
      ignore_errors: true
...
