---
- name: deploy TREX profiles
  include_tasks: trex/profile.yaml
  loop: "{{ trex_test_config }}"
  loop_control:
    loop_var: trex_test_config_item

- name: run additional tests
  block:
    - name: get all trexapps
      k8s_info:
        namespace: "{{ cnf_namespace }}"
        kind: TRexApp
      register: trex_apps

    - name: set trex app count to default 0
      set_fact:
        trex_apps_count: 0

    - name: increment trex_app_count for apps with valid duration
      set_fact:
        trex_apps_count: "{{ trex_apps_count|int + 1 }}"
      loop: "{{ trex_apps.resources }}"
      when: "'duration' in item.spec and item.spec.duration != -1"

    - debug: var=trex_apps_count

    - name: wait trex app run complete event
      k8s_info:
        namespace: "{{ cnf_namespace }}"
        kind: Event
        field_selectors:
          - "reason==TestCompleted"
          - "involvedObject.kind=TRexApp"
      register: evts
      retries: "{{ trex_tests_retry_mins_count|default(60) }}"
      delay: 60
      until: "evts.resources|length >= trex_apps_count|int"

  when:
   - trex_tests_wait | bool
